### ISSUE TITLE
Error during compiling. 'class FanRPM' has no member named 'multiplier'

### ISSUE THREAD

**Issue by Jasimo** [svenjust/room-ventilation-system#10]
Just tried to compile V.021, got the follwing error:
`FanControl.h:103:10: error: 'class FanRPM' has no member named 'multiplier'

     rpm_.multiplier() = static_cast<FanRPM::multiplier_t>(FanRPM::RPM_MULTIPLIER_BASE / ipr);

          ^

FanControl.h:103:45: error: 'multiplier_t' in 'class FanRPM' does not name a type

     rpm_.multiplier() = static_cast<FanRPM::multiplier_t>(FanRPM::RPM_MULTIPLIER_BASE / ipr);

                                             ^

FanControl.h:103:59: error: 'RPM_MULTIPLIER_BASE' is not a member of 'FanRPM'

     rpm_.multiplier() = static_cast<FanRPM::multiplier_t>(FanRPM::RPM_MULTIPLIER_BASE / ipr);

                                                           ^

'class FanRPM' has no member named 'multiplier'`

rgs
Jan

**Comment by schreter** [comment]
Hi Jan,

FanRPM ist eine Lib. Arduino IDE macht leider kein Refesh (na ja, IMHO verdient es die Bezeichnung IDE gar nicht:)).

Ich nehme an, IDE schließen und neu öffnen sollte es beheben.

Ivan

**Comment by Jasimo** [comment]
Hallo Ivan,

das hatte ich schon probiert, leider ohne Erfolg, komisch.

Gruß
Jan

**Comment by schreter** [comment]
Hi Jan,

seltsam. Ich habe gerade probiert die neueste Version zu kompilieren und es ging ohne Probleme.

Hast du nur die drei Fehler oder auch weitere? Kann es sein, dass dein Arduino IDE zu alt oder "zu neu" ist? Ich habe 1.8.5.

Wie hast du die Libs installiert? Via link_libs.sh oder manuell kopiert (dann muss du Updates auch kopieren)?

Welches OS hast du für Entwicklung genutzt?

Gruss,

Ivan

**Comment by Jasimo** [comment]
Ich nutze die 1.8.8.
Hatte die jedoch bei der vorherigen Version (die ohne die Apassung bezüglich Impulse pro Umdrehungen) auch genutzt, hatte geklappt. Nun hab ich ja scheinbar Lüfter verbaut die 2 Impulse pro Umdrehung machen und wollte die neue Version mal testen. Meine Lüfter zicken derzeit auch ein wenig bei der Kalibrierung.

Ich nutze das ganze unter Windows 10 ;-)
Die Bibliotheken hab ich ich der IDE installiert und die fehlenden kopiert. Muss ich vielleicht den Ordner FanRPM irgendwo hin kopieren?
Gruss
Jan

**Comment by schreter** [comment]
Hi Jan,

Yep, du muss die Libraries updaten. IIRC habe ich nur die FanRPM geändert, das sollte reichen.

Wie die Pfade auf Win10 sind, kann ich dir leider nicht sagen.

Gruss,

Ivan

**Comment by Jasimo** [comment]
Jetzt klappt es, hab alles nochmal neu kopiert.
Ich lade es mal hoch und gucke.
Kann sein das ich mich nochmal melde bezüglich meinen LKüftern, bin nämlich noch auf Fehlersuche und hab mit Sven schon viel probiert.

Gruß
Jan
