### ISSUE TITLE
PID Tuning parameters

### ISSUE THREAD

**Issue by Jasimo** [svenjust/room-ventilation-system#11]
Hallo,
ich habe in meiner Pluggit P300 andere Lüfter verbaut es kommen bei mir zwei ebm-papst r3g225 ae19-12 zum Einsatz. Bei mir schlägt die Kalibrierung regelmäßig fehl, wenn ich es mit den folgenden Standard Parametern versuche:
```
static constexpr double aggKp  = 0.5,  aggKi = 0.1, aggKd  = 0.001;
static constexpr double consKp = 0.1, consKi = 0.1, consKd = 0.001;
```

senke ich diese Werte ab klappt die Kalibrierung, derzeit bin ich auf:
```
static constexpr double aggKp  = 0.25,  aggKi = 0.05, aggKd  = 0.001;
static constexpr double consKp = 0.05, consKi = 0.05, consKd = 0.001;
```

den Tipp bekam ich von Sven im FHEM-Forum, leider hab ich kein Oszilloskop um das vernünftig zu tunen, wie weit kann ich denn mit den Werten Kp, Ki, Kd runter, es scheint als ob es durch weiteres Absenken stabiler werden könnte.
Gruß
Jan

**Comment by svenjust** [comment]
Hallo Jan!

> wie weit kann ich denn mit den Werten Kp, Ki, Kd runter

Im Prinzip beliebig weit, die Regelung der Lüfterdrehzahlen wird dann nur langsamer. Zu Bedeutung der Parameter siehe https://de.wikipedia.org/wiki/Regler

Zum Erreichen der Solldrehzahl werden bei einer Differenz von mehr als 1000 U/min zwischen der Soll- und Istdrehzahl die Parameter aggKp,  aggKi und aggKd verwendet. Wenn die Differenz kleiner als 1.000 U/min ist, dann werden die (kleineren) Parameter consKp, consKi, consKd verwendet. Ziel dabei ist, bei großer Differenz schnell die Solldrehzahl zu erreichen, siehe https://github.com/svenjust/room-ventilation-system/blob/b5b76cc4fead0a76dfd345f1fed9a546a3547fcd/Sourcecode/KWLctl/FanControl.cpp#L115


**NEU**: plotfans.py: Ein Script zur Visualisierung der Soll-, Istdrehzahl und PWM Signal der Lüfter. Das Script benötigt die Logausgabe der Lüfter, siehe https://github.com/svenjust/room-ventilation-system/blob/master/Docs/debug_fans/plotfans.py

Um eine Logausgabe für die Lüfter mit Soll-, Istdrehzahl und PWM Signal zu bekommen ist das folgende Vorgehen möglich:

Um die Logdatei zu erzeugen, muss die Software für den Controller mit dem `#define DEBUG` kompiliert werden.

 Die Übertragung kann für jeden Lüfter einzeln aktiviert werden.
```
   mosquitto_pub -t d15/debugset/kwl/fan1/getvalues -m on
   mosquitto_pub -t d15/debugset/kwl/fan2/getvalues -m on
```

Die übertragenen Werte können mit der folgenden Zeile in einer Datei "/tmp/debug.log" protokolliert werden:
`   mosquitto_sub -v -h localhost -t "d15/debugstate/#" > /tmp/debug.log`

Die Werte aus der Datei "/tmp/debug.log" können durch das Script plotfans.py dargestellt werden.

AUFRUF: `python <Pfad zu Script>\plotfans.py --infile /tmp/debug.log --out /tmp`
`python <Pfad zu Script>\plotfans.py -h` zeigt die Aufrufparameter

VG Sven

**Comment by Jasimo** [comment]
Hallo Sven,
ich debugge die Werte dann wärend einer Kalibrierung oder im normalen PROP Betrieb?
Könnte man nicht in den Code etwas wie PIDAutotune implementieren um die Werte für den verbauten Lüfter herauszubekommen?
https://playground.arduino.cc/Code/PIDAutotuneLibrary
Gruß Jan

**Comment by Jasimo** [comment]
hier die Grafen der Fans, Anlage lief auf Stufe1
![plot_fan1](https://user-images.githubusercontent.com/2403869/51535215-1e84a980-1e48-11e9-9d82-a9b9b375fe96.png)
![plot_fan2](https://user-images.githubusercontent.com/2403869/51535224-22b0c700-1e48-11e9-8272-c78496b02170.png)

**Comment by svenjust** [comment]
Die erkannten Drehzahlen, in den Bildern "rpm" genannt, sind viel zu unregelmäßig, da hilft es nicht an den PID Parametern zu schrauben. Das Problem liegt bei den gemessenen Drehzahlen. In beiden Bildern ist schön zu sehen, dass die Ansteuerung der Lüfter mit dem PWM Signal (im Bild tfs) stabil ist. 


Hörst Du den ungleichmäßigen Lauf der Lüfter oder laufen die Lüfter stabil?

**Comment by Jasimo** [comment]
Das ist ja das komische, die Lüfter schwanken hörbar und optisch überhaupt nicht. An der PWM Frequenz kann es auch nicht liegen, oder?

**Comment by svenjust** [comment]
Lt. der Papst-Spec R3G225RE0703-BA-GER.pdf, Seite 9, sollen die Lüfter mit 1-10kHz PWM angesteuert werden. Der Arduino Mega verwendet per default 490 Hz, dieser Wert wird bisher nicht geändert. Ob dies ein Problem ist, weiß ich nicht.

Die Lüfter werden an Pin 44 und 46 mit dem PWM Signal versorgt. Auf dem Arduino Mega ist Timer 5 für die Steuerung zuständig, siehe http://sobisource.com/arduino-mega-pwm-pin-and-frequency-timer-control/

Du könntest versuchen, in der Datei KWLctl.ino, Zeile 75 den folgenden Code zu ergänzen:
` TCCR5B = (TCCR5B & 0xF8) | 0x02 ;  # Timer 5, Divisor 8, Frequency  3.921 KHz`

Neu kompilieren, Drehzahlen loggen und visualisieren.

**Comment by Jasimo** [comment]
Hallo Sven,
ich mache das heute Abend mal, kaputt gehen kann da nix, oder?
Bin ja froh das die Kiste überhaupt wieder läuft ;-)
Gruß
Jan

**Comment by svenjust** [comment]
Hallo Jan,
ich kann die Änderung erst heute Abend testen. Dann warte doch, bis ich heute Abend probiert habe, ich melde mich nachfolgend. Ich sehe mir die Änderung dann auch im Oszilloskop an, um sicher zu gehen, dass die Codeänderung auch eine Änderung der Frequenz bringt.

VG Sven

**Comment by Jasimo** [comment]
so machen wir es.

**Comment by svenjust** [comment]
Hallo Jan,

obige Codezeile führt zu der Frequenzänderung. Bitte in KWLctl.ino ergänzen, so dass es wie folgt aussieht:
```
void setup()
{
Serial.begin(57600); // Serielle Ausgabe starten

// Timebase for PWM Signal
TCCR5B = (TCCR5B & 0xF8) | 0x02 ; // Timer 5, Divisor 8, Frequency 3.921 KHz

// *** TFT AUSGABE ***
```

**Comment by svenjust** [comment]
Vorher:
![screenshot_20190122_17_24_18](https://user-images.githubusercontent.com/11327892/51552546-12611200-1e71-11e9-8550-6afb565ea8b8.jpg)

Nach Codeänderung: 3,93 kHz
![screenshot_20190122_17_45_56](https://user-images.githubusercontent.com/11327892/51552576-2ad12c80-1e71-11e9-8d9a-79a17d2e59f0.jpg)

**Comment by Jasimo** [comment]
mit der Anpassung bekomme ich keine erfolgreiche Kalibrierung hin ;-(
Kommt nicht mal über Stufe1 in der Kalibrierung

**Comment by svenjust** [comment]
Hast Du die Logdatei oder Plots?

**Comment by Jasimo** [comment]
Hier die Grafen vom Kalibrierungsversuch
![plot_fan1](https://user-images.githubusercontent.com/2403869/51556796-6ec92f00-1e7b-11e9-8eb4-b765ea7be3a9.png)
![plot_fan2](https://user-images.githubusercontent.com/2403869/51556809-7557a680-1e7b-11e9-87dd-4399868b83b5.png)
Was hab ich blos für sch.... Lüfter verbaut

**Comment by Jasimo** [comment]
Ich bin glaube ich ein Stück weiter gekommen, eine Änderung von FALLING auf RISING brachte das folgende Ergebnis bei der Kalibrierung, wohlgemerkt wieder mit der standard PWM Frequenz des Arduino. Jedoch mit
```
static constexpr double aggKp  = 0.05,  aggKi = 0.01, aggKd  = 0.001;
static constexpr double consKp = 0.01, consKi = 0.01, consKd = 0.001;
```

![plot_fan1](https://user-images.githubusercontent.com/2403869/51563070-a4761400-1e8b-11e9-9f31-8483c1b83ee8.png)
![plot_fan2](https://user-images.githubusercontent.com/2403869/51563078-a8a23180-1e8b-11e9-962c-1ace630ac80b.png)

**Comment by svenjust** [comment]
Ich habe einen Lüfter der Anlage an meine Steuerung gehängt. Dann habe ich die folgenden Änderungen in der KWLctl.ino gemacht (ist eigentlich unwichtig, da der Standardwert eingestellt wird. Dies zeigt auch die Messung mit dem Oszilloskop:
``` 
  // Timebase for PWM Signal
  //TCCR5B = (TCCR5B & 0xF8) | 0x02 ; // Timer 5, Divisor 8, Frequency 3.921 KHz
  TCCR5B = (TCCR5B & 0xF8) | 0x03 ; // Timer 5, Divisor 64, Frequency 490.1 Hz            // default
  //TCCR5B = (TCCR5B & 0xF8) | 0x05 ; // Timer 5, Divisor 1024, Frequency 30.63 Hz
```  
In der FanControl.cpp ist geändert:
```
static constexpr double aggKp  = 0.1,  aggKi = 0.1, aggKd  = 0.001;
static constexpr double consKp = 0.025, consKi = 0.01, consKd = 0.01;
``` 
Damit bekomme ich im Modus PID die folgenden Werte:
![plot_fan2](https://user-images.githubusercontent.com/11327892/51562836-08e4a380-1e8b-11e9-97f2-7ba3d0060d7c.png)

Aktuell weiß ich nicht, warum bei Dir die gemessene Drehzahl so schwankt. Die gemessene Drehzahl ist scheinbar der Grund für die nicht durchlaufende Kalibrierung.

VG Sven

**Comment by svenjust** [comment]
Das sieht sehr gut aus! Das ist so korrekt.

Bezüglich der PWM Frequenz habe ich im Laufe des Abends auch die besten Erfahrungen mit der Standardfrequenz gemacht, etwa 490 Hz.

Das Triggern auf RISING hatte Ivan auch mal erwähnt, bei mir geht RISING und FALLING problemlos. Ich ändere aber im Sourcecode auf RISING. Die PID Parameter funktionieren bei mir auch, auch diese wandern in den master.

VG Sven

**Comment by Jasimo** [comment]
Supi, Dir nochmals VIELEN DANK! Natürlich auch an Ivan. Zum Abschluß nochmal grafen im normalen Betrieb (Stufe2)
![plot_fan1](https://user-images.githubusercontent.com/2403869/51564357-5531e280-1e8f-11e9-8ba9-8b33a90d0213.png)
![plot_fan2](https://user-images.githubusercontent.com/2403869/51564362-57943c80-1e8f-11e9-8fc4-ed0569b0c5a6.png)

Gruß
Jan

**Comment by svenjust** [comment]
Das sieht alles ok, top!

**Comment by schreter** [comment]
Hi Jan,

Sorry, ich bin erst jetzt online. Aber, ich wollte auch vorschlagen, mit RISING vs. FALLING zu probieren. Freut mich zu hören, dass es jetzt tut und gut zu wissen, dass ich nicht der einzige bin, der das Problem hatte :-).

Bei mir waren die Messungen noch erratischer - ich hatte doppelte und manchmal dreifache Signale (im Bereich von Mikrosekunden). Hat mich auch in den Wahnsinn getrieben, bis ich es endlich durch trial and error rausgefunden hatte. Ich habe mittlerweile auch Filtering eingebaut, damit solche doppelte Spitzen rausgefiltert werden.Seitdem läuft es bei mir mit RISING zuverlässig, mit FALLING aber nicht - ich habe dann auch so erratische Messwerte. Möglicherweise fehlt irgendwo ein Filterkondensator oder so, ich bin da kein Experte.

Leider habe ich keinen brauchbaren Oszilloskop, nur so ein uraltes analoges Teil, daher ist es schwierig zu analysieren (mit Oszilloskop läuft es ja :-).

Gruss,

Ivan

**Comment by Jasimo** [comment]
Ja, ich bin auch heilfroh das es nun läuft, vielleicht könnte man auf einem zukünfigen PCB schon mal etwas vorsehen für einen Kondensator, muss ja nicht zwingend bestückt werden, wenn es auch so läuft.
Jetzt kann ich mich endlich an das externe Display machen, das ist bei mir noch offen

**Comment by svenjust** [comment]
> vielleicht könnte man auf einem zukünfigen PCB schon mal etwas vorsehen für einen Kondensator, muss ja nicht zwingend bestückt werden, wenn es auch so läuft.

Sicher kann ich den Kondensator bei neuen Platinen vorsehen. Ich stelle mir nur die Frage, ob er zu einer entscheidenden Glättung des Signals führt. Evtl. ist ein Pullup-Widerstand von 4,7k an der Tacholeitung und das Ausschalten des Arduino-internen Pullup-Widerstands besser geeignet. Da mein Lüfter bei RISING und FALLING vernünftige Signale liefert, bin ich hier auf Zuarbeit angewiesen.

In der Platine sehe ich Kondensator und Widerstand vor.
