### ISSUE TITLE
Impulse pro Umdrehung für Tachosignal

### ISSUE THREAD

**Issue by svenjust** [svenjust/room-ventilation-system#8]
In den Lüftungsanlagen sind unterschiedliche Lüfter verbaut. So ist die Pluggit P300 auch mit Lüftern der Serie r3g**225** (ansonsten wohl r3g**190**) ausgeliefert worden. Diese Lüfter liefern anscheinend 2 Impulse pro Umdrehung als Tachosignal. Die bisherige Implementierung geht von 1 Impuls pro Umdrehung aus.

Es soll in der Steuerung für die Lüfter ein Parameter PulsesPerRevolutionFan1 bzw. PulsesPerRevolutionFan2 ergänzt werden, der die Anzahl der Impulse am Tachosignal für eine Umdrehung des Lüfters enthält. Der Standardwert beider Parameter ist 1. Die Parameter sollen in der Datei UserConfig.h überschrieben werden können. Eine Änderung beider Parameter zur Laufzeit (am Display oder per mqtt) erscheint NICHT notwendig, die Parameter sind hardwareabhängig fest für eine Hardwarekonfiguration.

Referenz: https://forum.fhem.de/index.php/topic,83025.msg883495.html#msg883495 und https://www.ebmpapst.com/media/content/info-center/downloads_10/catalogs/compactfansen2011/compactfanssingle2011/DC-Luefter-Specials_2016_01_D.pdf

**Comment by schreter** [comment]
FYI, working on it. The first untested version is at https://github.com/schreter/room-ventilation-system/commit/e268139ac739b8ff0973632512f22bae7331b40d.
